### ISSUE TITLE
General: Switching from portrait to landscape mode on the iPad will zoom the screen in. Additionally, the user cannot zoom back out to fit the site to the screen.

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Lyra-Livich#45]

**Comment by arielcebudigital** [comment]
please provide screenshot since we don't have actual device yet, but working in our end..

**Comment by bernardtitan** [comment]
Note that it is zoomed in enough that the Contact button is off-screen

![general - 01](https://cloud.githubusercontent.com/assets/11186359/7174937/6654b3ee-e441-11e4-94da-ffbd3d676601.jpg)
