### ISSUE TITLE
General: Remove the fade-in animation from all pages in the site.

### ISSUE THREAD

**Issue by bernardtitan** [titan-cebu/Lyra-Livich#8]
Unless, it is specified in the design as a sticky note, we shouldn't include animations. Additionally, this particular animation hides the page content until the user starts to scroll down

**Comment by bernardtitan** [comment]
All the animation code is still littering up the code, they should be removed entirely

**Comment by arielcebudigital** [comment]
from jolene: hey, so the main reason why we are not rolling it out with our current builds, are that we first have to set the standards in place and also get the designer to design within the coding standards
[3/30/2015 11:34:20 PM] Jo Erasmus: in this case I'm happy for you to keep the banner transitions but if you can please remove that from the content for now
